SCANNER_RESULTS = [
    {
        "ticker": "DQ",
        "scanner": "Don't Dilute Me",
        "price": 13.42,
        "change_pct": 4.8,
        "edge_score": 91,
        "risk": "Medium",
        "entry": "13.10 - 13.55",
        "stop": "12.62",
        "target_1": "15.20",
        "target_2": "16.80",
        "dilution_flag": "Low",
        "setup": "Quality reversal near support with RSI turning up and no obvious recent dilution flag.",
    },
    {
        "ticker": "INLF",
        "scanner": "Panic Reversal",
        "price": 0.0626,
        "change_pct": 34.05,
        "edge_score": 78,
        "risk": "High",
        "entry": "0.058 - 0.064",
        "stop": "0.050",
        "target_1": "0.073 VWAP",
        "target_2": "0.085 - 0.10",
        "dilution_flag": "High",
        "setup": "Capitulation bounce after massive flush. Volume returned, RSI recovering, VWAP reclaim still pending.",
    },
    {
        "ticker": "QBTS",
        "scanner": "Early Explosion",
        "price": 5.84,
        "change_pct": 2.1,
        "edge_score": 84,
        "risk": "Medium",
        "entry": "5.65 - 5.90",
        "stop": "5.38",
        "target_1": "6.55",
        "target_2": "7.20",
        "dilution_flag": "Medium",
        "setup": "Tight consolidation with improving momentum and possible sector tailwind.",
    },
]
